// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aotnfnororzrnevuafjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvdG5mbm9yb3J6cm5ldnVhZmprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMjM3MDksImV4cCI6MjA1MDg5OTcwOX0.ltTfjCmPucKdABm4vGHN61kmedSANC-CcMytKXmgt_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);